### ISSUE TITLE
[bug] calling InputChoice.MenuButton().Popup() can crash

### ISSUE THREAD

**Issue by mark-summerfield** [pwiecz/go-fltk#64]
Run the tiny eg below. Press F2 to pop up the InputChoice menu. Correctly, nothing happens because the menu is empty. Then press F2 again: crash!
```go
package main

import (
	"fmt"

	"github.com/pwiecz/go-fltk"
)

func main() {
	const (
		width      = 200
		height     = 80
		lineHeight = height / 2
	)
	fltk.SetScheme("oxy")
	window := fltk.NewWindow(width, height)
	window.SetLabel("InputChoice")
	vbox := fltk.NewFlex(0, 0, width, height)
	box := fltk.NewBox(fltk.DOWN_FRAME, 0, 0, width, lineHeight,
		"(Nothing Chosen)")
	choice := fltk.NewInputChoice(0, lineHeight, width, lineHeight)
	fmt.Println(box, choice)
	vbox.End()
	window.SetEventHandler(func(event fltk.Event) bool {
		if fltk.EventType() == fltk.KEY && fltk.EventKey() == fltk.F2 {
			if menu := choice.MenuButton(); menu != nil {
				menu.Popup()
			}
		}
		return false
	})
	window.Show()
	fltk.Run()
}
```
My crash output:
```
&{{0x2186ef0 0 3 0 0 0 <nil> <nil>}} &{{{0x21870d0 0 4 0 0 0 <nil> <nil>}} 0xc00009e0f0 0xc0000b40e0 5}
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x54338e]

runtime stack:
runtime.throw({0x653997?, 0x7ffead511618?})
	/home/mark/opt/go/src/runtime/panic.go:1047 +0x5d fp=0x7ffead511510 sp=0x7ffead5114e0 pc=0x4aa9fd
runtime.sigpanic()
	/home/mark/opt/go/src/runtime/signal_unix.go:821 +0x3e9 fp=0x7ffead511570 sp=0x7ffead511510 pc=0x4bf0c9

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x5071b0, 0xc0000bfc20)
	/home/mark/opt/go/src/runtime/cgocall.go:157 +0x5c fp=0xc0000bfbf8 sp=0xc0000bfbc0 pc=0x47c3dc
github.com/pwiecz/go-fltk._Cfunc_go_fltk_MenuButton_popup(0x216e7c0)
	_cgo_gotypes.go:2554 +0x45 fp=0xc0000bfc20 sp=0xc0000bfbf8 pc=0x4fd505
github.com/pwiecz/go-fltk.(*MenuButton).Popup.func1(0xc0000bfc70?)
	/home/mark/opt/gows/pkg/mod/github.com/pwiecz/go-fltk@v0.0.0-20230324100514-db7b885634cb/menu.go:139 +0x46 fp=0xc0000bfc58 sp=0xc0000bfc20 pc=0x4ff126
github.com/pwiecz/go-fltk.(*MenuButton).Popup(0xc00000ffbf?)
	/home/mark/opt/gows/pkg/mod/github.com/pwiecz/go-fltk@v0.0.0-20230324100514-db7b885634cb/menu.go:139 +0x19 fp=0xc0000bfc70 sp=0xc0000bfc58 pc=0x4ff0b9
main.main.func1(0x63a4c0?)
	/home/mark/tmp/inputchoice/choice.go:27 +0x85 fp=0xc0000bfc90 sp=0xc0000bfc70 pc=0x5037c5
github.com/pwiecz/go-fltk.(*eventHandlerMap).invoke(...)
	/home/mark/opt/gows/pkg/mod/github.com/pwiecz/go-fltk@v0.0.0-20230324100514-db7b885634cb/enumerations.go:315
github.com/pwiecz/go-fltk._go_eventHandler(0x61a0?, 0x8)
	/home/mark/opt/gows/pkg/mod/github.com/pwiecz/go-fltk@v0.0.0-20230324100514-db7b885634cb/enumerations.go:335 +0x51 fp=0xc0000bfcb8 sp=0xc0000bfc90 pc=0x4fe431
_cgoexp_00c77b302643__go_eventHandler(0x7ffead512114)
	_cgo_gotypes.go:7099 +0x25 fp=0xc0000bfcd0 sp=0xc0000bfcb8 pc=0x5012a5
runtime.cgocallbackg1(0x501280, 0xc0000bfe80?, 0x0)
	/home/mark/opt/go/src/runtime/cgocall.go:315 +0x2b1 fp=0xc0000bfd98 sp=0xc0000bfcd0 pc=0x47c8d1
runtime.cgocallbackg(0xc0000061a0?, 0x300000002?, 0xc0000061a0?)
	/home/mark/opt/go/src/runtime/cgocall.go:234 +0x109 fp=0xc0000bfe28 sp=0xc0000bfd98 pc=0x47c589
runtime.cgocallbackg(0x501280, 0x7ffead512114, 0x0)
	<autogenerated>:1 +0x2f fp=0xc0000bfe50 sp=0xc0000bfe28 pc=0x4d9c0f
runtime.cgocallback(0x47c405, 0x506520, 0xc0000bfee0)
	/home/mark/opt/go/src/runtime/asm_amd64.s:998 +0xb4 fp=0xc0000bfe78 sp=0xc0000bfe50 pc=0x4d7514
runtime.systemstack_switch()
	/home/mark/opt/go/src/runtime/asm_amd64.s:463 fp=0xc0000bfe80 sp=0xc0000bfe78 pc=0x4d5520
runtime.cgocall(0x506520, 0xc0000bfee0)
	/home/mark/opt/go/src/runtime/cgocall.go:167 +0x85 fp=0xc0000bfeb8 sp=0xc0000bfe80 pc=0x47c405
github.com/pwiecz/go-fltk._Cfunc_go_fltk_run()
	_cgo_gotypes.go:6634 +0x48 fp=0xc0000bfee0 sp=0xc0000bfeb8 pc=0x4fe148
github.com/pwiecz/go-fltk.Run(...)
	/home/mark/opt/gows/pkg/mod/github.com/pwiecz/go-fltk@v0.0.0-20230324100514-db7b885634cb/fltk.go:22
main.main()
	/home/mark/tmp/inputchoice/choice.go:33 +0x1ab fp=0xc0000bff80 sp=0xc0000bfee0 pc=0x50370b
runtime.main()
	/home/mark/opt/go/src/runtime/proc.go:250 +0x207 fp=0xc0000bffe0 sp=0xc0000bff80 pc=0x4ad2e7
runtime.goexit()
	/home/mark/opt/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000bffe8 sp=0xc0000bffe0 pc=0x4d7741

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/mark/opt/go/src/runtime/proc.go:381 +0xd6 fp=0xc000068fb0 sp=0xc000068f90 pc=0x4ad716
runtime.goparkunlock(...)
	/home/mark/opt/go/src/runtime/proc.go:387
runtime.forcegchelper()
	/home/mark/opt/go/src/runtime/proc.go:305 +0xb0 fp=0xc000068fe0 sp=0xc000068fb0 pc=0x4ad550
runtime.goexit()
	/home/mark/opt/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000068fe8 sp=0xc000068fe0 pc=0x4d7741
created by runtime.init.6
	/home/mark/opt/go/src/runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/mark/opt/go/src/runtime/proc.go:381 +0xd6 fp=0xc000069780 sp=0xc000069760 pc=0x4ad716
runtime.goparkunlock(...)
	/home/mark/opt/go/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
	/home/mark/opt/go/src/runtime/mgcsweep.go:278 +0x8e fp=0xc0000697c8 sp=0xc000069780 pc=0x49a48e
runtime.gcenable.func1()
	/home/mark/opt/go/src/runtime/mgc.go:178 +0x26 fp=0xc0000697e0 sp=0xc0000697c8 pc=0x48f966
runtime.goexit()
	/home/mark/opt/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000697e8 sp=0xc0000697e0 pc=0x4d7741
created by runtime.gcenable
	/home/mark/opt/go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000090000?, 0x66adc8?, 0x1?, 0x0?, 0x0?)
	/home/mark/opt/go/src/runtime/proc.go:381 +0xd6 fp=0xc000069f70 sp=0xc000069f50 pc=0x4ad716
runtime.goparkunlock(...)
	/home/mark/opt/go/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x75f460)
	/home/mark/opt/go/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc000069fa0 sp=0xc000069f70 pc=0x4983d3
runtime.bgscavenge(0x0?)
	/home/mark/opt/go/src/runtime/mgcscavenge.go:628 +0x45 fp=0xc000069fc8 sp=0xc000069fa0 pc=0x4989a5
runtime.gcenable.func2()
	/home/mark/opt/go/src/runtime/mgc.go:179 +0x26 fp=0xc000069fe0 sp=0xc000069fc8 pc=0x48f906
runtime.goexit()
	/home/mark/opt/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000069fe8 sp=0xc000069fe0 pc=0x4d7741
created by runtime.gcenable
	/home/mark/opt/go/src/runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0x1a0?, 0x75f8a0?, 0x60?, 0x78?, 0xc000068770?)
	/home/mark/opt/go/src/runtime/proc.go:381 +0xd6 fp=0xc000068628 sp=0xc000068608 pc=0x4ad716
runtime.runfinq()
	/home/mark/opt/go/src/runtime/mfinal.go:193 +0x107 fp=0xc0000687e0 sp=0xc000068628 pc=0x48e9a7
runtime.goexit()
	/home/mark/opt/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000687e8 sp=0xc0000687e0 pc=0x4d7741
created by runtime.createfing
	/home/mark/opt/go/src/runtime/mfinal.go:163 +0x45
exit status 2
```

**Comment by pwiecz** [comment]
Thanks for the report.
I've tried running an equivalent code in C++:
`#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Input_Choice.H>

Fl_Input_Choice *choice = nullptr;
class GWindow : public Fl_Window {
public:
  GWindow(int w, int h)
    : Fl_Window(w, h) {}
  int handle(int event) override {
    if (Fl::event() == FL_KEYDOWN && Fl::event_key() == FL_F + 2) {
      choice->menubutton()->popup();
    }
    return 1;
  }    
        
};  
int main() {
    GWindow win(100,100);
    choice = new Fl_Input_Choice(10,10,80,25,"choice");
    win.end();
    win.resizable(win);
    win.show();
    return (Fl::run());
}  
`
and it also crashed. So it may not be easy to fix on the Go side. 
If it's a bug on the C++ side, probably it'd be safest to to find a workaround (maybe not call `Popup()` for empty menu).
In the meantime we should report it to the fltk-team and see what's their response.

**Comment by MoAlyousef** [comment]
It crashes with Rust as well, so I’ve added a check in the popup function which checks the size of the menu.
